FROM golang as builder

WORKDIR /go/src/github.com/meiliangwhut/hello/

COPY app.go    .

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o app .  

FROM alpine
COPY --from=builder /go/src/github.com/meiliangwhut/hello/app /app

EXPOSE 3000 
CMD ["/app"]


